//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_Ivo_Ojvan.numberToWord {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="numberToWord.NumberConversionSoapType")]
    public interface NumberConversionSoapType {
        
        // CODEGEN: Generating message contract since element name NumberToWordsResult from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponse NumberToWords(NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponse> NumberToWordsAsync(NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest request);
        
        // CODEGEN: Generating message contract since element name NumberToDollarsResult from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponse NumberToDollars(NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponse> NumberToDollarsAsync(NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequestBody Body;
        
        public NumberToWordsRequest() {
        }
        
        public NumberToWordsRequest(NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong ubiNum;
        
        public NumberToWordsRequestBody() {
        }
        
        public NumberToWordsRequestBody(ulong ubiNum) {
            this.ubiNum = ubiNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponseBody Body;
        
        public NumberToWordsResponse() {
        }
        
        public NumberToWordsResponse(NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToWordsResult;
        
        public NumberToWordsResponseBody() {
        }
        
        public NumberToWordsResponseBody(string NumberToWordsResult) {
            this.NumberToWordsResult = NumberToWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequestBody Body;
        
        public NumberToDollarsRequest() {
        }
        
        public NumberToDollarsRequest(NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal dNum;
        
        public NumberToDollarsRequestBody() {
        }
        
        public NumberToDollarsRequestBody(decimal dNum) {
            this.dNum = dNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponseBody Body;
        
        public NumberToDollarsResponse() {
        }
        
        public NumberToDollarsResponse(NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToDollarsResult;
        
        public NumberToDollarsResponseBody() {
        }
        
        public NumberToDollarsResponseBody(string NumberToDollarsResult) {
            this.NumberToDollarsResult = NumberToDollarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NumberConversionSoapTypeChannel : NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType>, NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType {
        
        public NumberConversionSoapTypeClient() {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponse NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType.NumberToWords(NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest request) {
            return base.Channel.NumberToWords(request);
        }
        
        public string NumberToWords(ulong ubiNum) {
            NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest inValue = new NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest();
            inValue.Body = new NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponse retVal = ((NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType)(this)).NumberToWords(inValue);
            return retVal.Body.NumberToWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponse> NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType.NumberToWordsAsync(NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest request) {
            return base.Channel.NumberToWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NTP_Ivo_Ojvan.numberToWord.NumberToWordsResponse> NumberToWordsAsync(ulong ubiNum) {
            NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest inValue = new NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequest();
            inValue.Body = new NTP_Ivo_Ojvan.numberToWord.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            return ((NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType)(this)).NumberToWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponse NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType.NumberToDollars(NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollars(request);
        }
        
        public string NumberToDollars(decimal dNum) {
            NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest inValue = new NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest();
            inValue.Body = new NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponse retVal = ((NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType)(this)).NumberToDollars(inValue);
            return retVal.Body.NumberToDollarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponse> NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType.NumberToDollarsAsync(NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NTP_Ivo_Ojvan.numberToWord.NumberToDollarsResponse> NumberToDollarsAsync(decimal dNum) {
            NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest inValue = new NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequest();
            inValue.Body = new NTP_Ivo_Ojvan.numberToWord.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            return ((NTP_Ivo_Ojvan.numberToWord.NumberConversionSoapType)(this)).NumberToDollarsAsync(inValue);
        }
    }
}
